### Step 1. Create a custom metric descriptor [POST /organizations/{org_id}/metric_descriptors]

**Note that this endpoint is identical to the V1 endpoint.
Its documentation has been copied here for convenience in explaing the custom conversion upload flow.
AdStage may choose to release a V2 namespaced endpoint with a different feature set and shape in the future.**

Sets up a metric descriptor to allow data upload. Returns the url to allow upload.
You only need to do this step once per conversion column you want to created.
To get a list of conversion columns, see the Build Reports section - "Organization Metric Descriptors".

+ Parameters

    + `org_id` (integer) - The fetch id of the user's organization

+ Request (application/json)

    + Headers

            Authorization: Bearer de4dxxxxb33f
            Accept: application/json

    + Attributes

        + `name`: "Sales Leads: A+" (string, required) - The full name of the conversion column.
        + `short_name`: "A+ Leads" (string, required) - A shorter version of name for table column headers.
        + `tooltip`: "Leads scored A+ in Salesforce" (string, required) - A text description of the converion for use in tooltips in AdStage products.

    + Body

            {
                "name": "Sales Leads: A+",
                "short_name": "A+ Leads",
                "tooltip": "Leads scored A+ in Salesforce"
            }

+ Response 201

    Note that in the response, the id is returned as `custom_conversions:{fetch id}:conversions`.
    You can use the link to find the appropriate URL for upload in Step 3 of the conversion upload process.

    + Attributes

        + id: "custom_conversions:14:conversions" (string) - The metric name reports reports will return when providing conversion metrics for this descriptor.
        + `_links` (object)
            + `adstage:custom_conversion_upload` (object)
                + href: "https://platform.adstage.io/api/organizations/40/metric_descriptors/14/conversions" (string) - The URL for Step 2, which will accept conversion data for this metric descriptor.

    + Body

            {
                "id": "custom_conversions:14:conversions",
                "category": "CUSTOM_CONVERSION",
                "type": "METRIC",
                "name": "Sales Leads: A+",
                "short_name": "A+ Leads",
                "tooltip": "Doesn't matter",
                "default_sort_order": "DESC",
                "format": "DEFAULT",
                "_links": {
                        "adstage:custom_conversion_upload": {
                            "href": "https://platform.adstage.io/api/organizations/40/metric_descriptors/14/conversions"
                        }
                }
            }
