## Custom Conversions [/v2/organizations/{org_id}/metric_descriptors]

The AdStage API allows users to create and associate metrics data with Custom Conversions.
For example, a user might maintain a spreadsheet attributing Sales Qualified Leads to a mixture of ads.
With this data regularly uploaded via the API, these metrics can be blended into results from the reporting APIs and can be accessed in the AdStage product.

There are two steps required to set up a new Custom Conversion in the API:

:[Create a Custom Metric Descriptor](organization_create_metric_descriptor.apib)

:[Post Metrics Data to the Custom Metric Descriptor](organization_metric_descriptor_create_conversions.apib)
