## Links

HAL resources may contain links to other related resources in the `_links` object.
Applications can follow the URLs in links to access these resources.

_Note that some links in the API responses may contain URLs for endpoints not documented here.
These are not maintained as stable for external users and are not supported.
Please check whether a link's endpoint is documented here before using it in your application.
Most supported HAL links for API customers are pagination related._

**Modified HAL response from a request to a user data endpoint**

```
{
  // The main response contains data about the user resource,
  // which was the item requested from the endpoint
  "admin": false,
  "avatar_url": "https://www.gravatar.com/avatar/123456",
  "created_at": 1522185933,
  "customer_status": "trialing",
  "default_organization_role": "OWNER",
  "email": "polarbear@adstage.io",
  "fetch_id": 1,
  "id": "/api/users/1",
  ...,

  // The _links section of the response returns links related to the given user,
  // such as a full description of the user's organization
  // and lists of the user's accounts
  "_links": {
    "adstage:organization": {
      "href": "http://platform.adstage.io/api/organizations/1"
    }

    // Occasionally links may include templates for URL parameters that can refine the request
    "adstage:list": [
      {
          "templated": true,
          "name": "adwords_accounts",
          "href": "http://platform.adstage.io/api/users/1/list_network_accounts/adwords{?limit,offset,sort_by,order,term}"
      },
      {
          "templated": true,
          "name": "bing_ads_accounts",
          "href": "http://platform.adstage.io/api/users/1/list_network_accounts/bing_ads{?limit,offset,sort_by,order,term}"
      },
      ...
    ],
    ...
  },
  ...
```
