## Building Reports [/organizations/{org_id}/build_report]

This endpoint is used to pull your advertising data. To use this you will need your token and your organization's fetch id.

Use this endpoint to pull reports at any level of reporting available within AdStage.

:[Basic Report](organization_index_build_report__basic.apib)

:[Time Series Report](organization_index_build_report__timeseries.apib)

:[Metric Descriptors](index_metric_descriptors.apib)

:[Network Metric Descriptors](metric_descriptors_show_network.apib)

:[Organization Metric Descriptors](organization_metric_descriptors_index.apib)
