### Retrieve Organization Metric Descriptors [GET /organizations/{org_id}/metric_descriptors]

This endpoint returns information about the names and formats of custom metrics created for a single organization.

These metric descriptors can be:
* (AdStage) Custom Conversions, describing user-uploaded custom data.
* Network Custom Conversions, describing conversion data imported from supported remote netwokrs (currently Facebook and LinkedIn).
* Calculated Metrics, describing user-defined combinations of other metrics (not supported in the V1 reporting endpoint).

Additionally, AdStage will automatically derive several metrics that are listed in this endpoint based on both AdStage and Network Custom Conversions:
* Conversion Value
* Cost per Conversion
* Conversion Rate
* Return on Ad Spend (ROAS)

+ Parameters

    + org_id: 40 (string)

        Which organization you want descriptors for.

+ Request

    + Headers

            Authorization: Bearer de4dxxxxb33f
            Accept: application/json

+ Response 200

    A list of columns that are available to pull via the reporting endpoint.

    + Attributes

        + `descriptors` (array)
            + (object)
                + id: "clicks" (string) - the identifier assigned to the metric in reports
                + `short_name`: "Clicks" (string) - a short human readable name for the metric
                + name: "Clicks" (string) - the full human readable name for the metric
                + tooltip: "Clicks shows how many times a user clicked on your ad" (string) - additional details about a metric, if available
                + format: "DEFAULT", "PERCENTAGE", "CURRENCY", "TEXT", "DECIMAL", "INTEGER" (enum[string]) - format for the metric (default is `INTEGER`)
                + type: "METRIC", "TEXT" (enum[string]) - whether the descriptor is for a metric or metadata
                + `is_adwords`: true (boolean) - if the metric is valid for the `adwords` network
                + `is_amazon`: true (boolean) - if the metric is valid for the `amazon` network
                + `is_bing_ads`: true (boolean) - if the metric is valid for the `bing_ads` network
                + `is_facebook`: true (boolean) - if the metric is valid for the `facebook` network
                + `is_gemini`: false (boolean) - if the metric is valid for the `gemini` network
                + `is_google_analytics`: false (boolean) - if the metric is valid for the `google_analytics` network
                + `is_linkedin`: true (boolean) - if the metric is valid for the `linkedin` network
                + `is_pinterest`: true (boolean) - if the metric is valid for the `pinterest` network
                + `is_quora`: true (boolean) - if the metric is valid for the `quora` network
                + `is_spotify`: true (boolean) - if the metric is valid for the `spotify` network
                + `is_twitter`: true (boolean) - if the metric is valid for the twitter network
                + `is_account`: true (boolean) - if the metric is valid for the account reporting level
                + `is_campaign`: true (boolean) - if the metric is valid for the campaign reporting level
                + `is_ad_group`: true (boolean) - if the metric is valid for the ad group reporting level
                + `is_ad`: true (boolean) - if the metric is valid for the ad reporting level
                + `is_keyword`: true (boolean) - if the metric is valid for keyword reporting level

    + Body

            [
                {
                    "id": "clicks",
                    "short_name": "Clicks",
                    "name": "Clicks",
                    "is_default": true,
                    "tooltip": "<b>Clicks</b> show how many times your ads have been clicked.",
                    "format": "DEFAULT",
                    "type": "METRIC",
                    "category": "PERFORMANCE",
                    "default_sort_order": "DESC",
                    "is_adwords": true,
                    "is_amazon": true,
                    "is_bing_ads": true,
                    "is_facebook": true,
                    "is_gemini": false,
                    "is_google_analytics": false,
                    "is_linkedin": true,
                    "is_pinterest": true,
                    "is_quora": true,
                    "is_spotify": true,
                    "is_twitter": true,
                    "is_account": true,
                    "is_campaign": true,
                    "is_ad_group": true,
                    "is_ad": true,
                    "is_keyword": true,
                    "is_post": null,
                    "is_company_status_update": null
                },
                {
                    "id": "impressions",
                    "short_name": "Impr.",
                    "name": "Impressions",
                    "is_default": true,
                    "tooltip": "<b>Impressions</b> show how many times your ads have been shown.",
                    "format": "DEFAULT",
                    "type": "METRIC",
                    "category": "PERFORMANCE",
                    "default_sort_order": "DESC",
                    "is_adwords": true,
                    "is_amazon": true,
                    "is_bing_ads": true,
                    "is_facebook": true,
                    "is_gemini": false,
                    "is_google_analytics": false,
                    "is_linkedin": true,
                    "is_pinterest": true,
                    "is_quora": true,
                    "is_spotify": true,
                    "is_twitter": true,
                    "is_account": true,
                    "is_campaign": true,
                    "is_ad_group": true,
                    "is_ad": true,
                    "is_keyword": true,
                    "is_post": null,
                    "is_company_status_update": null
                },
                {
                    "id": "ctr",
                    "short_name": "CTR",
                    "name": "CTR",
                    "is_default": true,
                    "tooltip": "<b>Clickthrough rate</b> shows how often people who saw your ad ended up clicking it.<br><br> CTR is clicks divided by impressions.<br><br> To improve your CTR, check out our <a href=\"http://blog.adstage.io/2013/05/23/5-tips-for-creating-effective-ppc-ads/\" target=\"_blank\">5 tips for creating effective ads</a>.",
                    "format": "PERCENTAGE",
                    "type": "METRIC",
                    "category": "PERFORMANCE",
                    "default_sort_order": "DESC",
                    "is_adwords": true,
                    "is_amazon": true,
                    "is_bing_ads": true,
                    "is_facebook": true,
                    "is_gemini": false,
                    "is_google_analytics": false,
                    "is_linkedin": true,
                    "is_pinterest": true,
                    "is_quora": true,
                    "is_spotify": true,
                    "is_twitter": true,
                    "is_account": true,
                    "is_campaign": true,
                    "is_ad_group": true,
                    "is_ad": true,
                    "is_keyword": true,
                    "is_post": null,
                    "is_company_status_update": null
                }
            ]
