## Custom Conversions [/organizations/{org_id}/metric_descriptors]

The AdStage custom metric descriptor endpoint will allow data to be uploaded to a custom column for any existing entities stored within AdStage.
You can then use these custom conversion columns in the reporting endpoints or in the AdStage product.
This requires a few steps to get data flowing:

:[Create a Custom Metric Descriptor](organization_create_metric_descriptor.apib)

:[Post Metrics Data to the Custom Metric Descriptor](organization_metric_descriptor_create_conversions.apib)
