## Authentication

AdStage uses HTTP header bearer tokens for API authentication.
Contact the AdStage Customer Success team at `support@adstage.io` or your organization's account manager to receive an authentication token.

### OAuth 2 Applications
If would like to create a application for multiple AdStage users, the AdStage API can serve as an OAuth 2 provider.
However, there is currently no self-service method to register new OAuth2 applications.
Contact the AdStage Customer Success team at `support@adstage.io` to have a `client_id` and `client_secret` provisioned for your application.
