# AdStage API Concepts

The AdStage API is a cross-network advertising API allowing access to Google Ads, Microsoft Ads, Facebook, LinkedIn, Twitter, Instagram, Gemini, and Google Analytics data from a unified interface.

AdStage's JSON APIs broadly allow developers to:
* Access data about their AdStage users, organizations, and advertising entities
* Upload custom data for use within the AdStage platform
* Pull customizable reports on advertising data in a single, normalized format

AdStage provides two API versions: V1, which is a fully stable and fully released API version, and V2, which is a fully stable version with release in progress.
Though V1 may occasionally be an appropriate choice to access certain legacy features not yet available in V2, in most cases V2 should be preferred due to its generally expanded feature set, shorter maintenance cycles, and faster performance.
When choosing a particular version, check the documentation in both versions before determining the best option.

Across endpoints and versions, AdStage APIs often refer to several key concepts, documented in this section.
The next sections group version-specific documentation for the API endpoints and common workflows.

:[Date Ranges](date_ranges.apib)

:[Entity IDs](entity_ids.apib)

:[HAL JSON](hal_json/root.apib)

:[Pagination](pagination.apib)

:[Authentication](authentication.apib)

:[API Status](api_status.apib)
