# Group AdStage API V2

This version of the AdStage API can be considered stable, with full release to external customers in progress.
Additional endpoints within V2 may be developed and/or released, and internal customer V2 endpoints may be documented and released to external customers in the future.

:[Custom Conversions](custom_conversions/root.apib)

:[Building Reports](building_reports/root.apib)
