## Building Reports [/organizations/{org_id}/build_report]

Use this endpoint to pull reports at any level of reporting available within AdStage, or to conveniently pull real-time reports with the same normalization scheme from supported external API providers such as Facebook Direct.
**The V1 endpoint does not support reporting on calculated metrics; choose the V2 endpoint if that feature is required.**

:[Basic Report](organization_create_build_report__basic.apib)

:[Time Series Report](organization_create_build_report__timeseries.apib)
