## Building Reports [/organizations/{org_id}/build_report]

This endpoint is used to pull your advertising data.

Use this endpoint to pull reports at any level of reporting available within AdStage, or to conveniently pull real-time reports with the same normalization scheme from supported external API providers such as Facebook Direct.

:[Basic Report](organization_create_build_report__basic.apib)

:[Time Series Report](organization_create_build_report__timeseries.apib)
