## Authentication

To get started using the AdStage API you will need an API token.
You can obtain one by contacting our support team.

### OAuth 2 Applications
If you are a developer that would like to create applications for multiple AdStage users, our API has OAuth 2 support, but we don't currently have a self-service way to create new OAuth2 applications.
Contact us and we can get you started with a `client_id` and `client_secret`.
