FORMAT: 1A
HOST: https://platform.adstage.io/api

# AdStage API

The AdStage API is a cross-network advertising API allowing access to AdWords,
Bing Ads, Facebook, LinkedIn, Twitter, Instagram, Gemini, and Google Analytics data from a unified
interface.

:[Authentication](authentication.apib)

:[Status](status.apib)

:[AdStage API Concepts](adstage_api_concepts.apib)

:[Basic Data](basic_data/root.apib)

:[Building Reports](building_reports/root.apib)

:[Building Reports](custom_conversions/root.apib)
