### Meta Fields

Metadata fields are typically strings, such as an ad's `title`, though in some cases, a meta field can be of another type, such as `budget_float` - the most recent budget for the entity cast to a float.
In these cases, the casted data type is appended to the string: `budget_float` will return a float.

Because meta fields are so rarely changed, AdStage does not currently provide an API endpoint to list all meta fields on-demand.
Instead, a comprehensive list of metadata fields is provided below for convenience.
In the future, AdStage may replace this with an API endpoint for meta field discovery.

#### Entity Names

Gives the displayable names of each entity (e.g. an ad) or parent entity (e.g. the campaign owning the ad).
Often useful for filtering reports based on substrings of a name when ads are created with stable naming conventions.

| UI Display Name        | API Field Name          |
| ---------------------- | ----------------------- |
| Network                | `network`               |
| Name                   | `name`                  |
| Account Name           | `account_name`          |
| Campaign Name          | `campaign_name`         |
| Ad Group / Ad Set Name | `ad_group_name`         |
| Ad Name                | `ad_name`               |

#### Currency Information

Gives the metadata needed to interpret currency metrics, such as spend, associated with the entity.

| UI Display Name        | API Field Name          |
| ---------------------- | ----------------------- |
| Currency Code          | `currency_code`         |
| Currency Symbol        | `currency_symbol`       |

#### Short IDs

Gives short form unique identifiers for each entity, matching ids generated by each remote ad network.
Prefer the more descriptive long form IDs for cases where a human may need to interpret the IDs.
For example, AdStage internally chooses the `entity_id` field as the main search field in its troubleshooting utilities.

| UI Display Name        | API Field Name          |
| ---------------------- | ----------------------- |
| Account ID             | `remote_account_id`     |
| Campaign ID            | `remote_campaign_id`    |
| Ad Group ID            | `remote_ad_group_id`    |
| Ad ID                  | `remote_ad_id`          |
| Keyword ID             | `remote_keyword_id`     |

#### Account Groups and Folders IDs

Gives short form unique identifiers for entity grouping constructs managed within the AdStage UI.
Folders represent groups of campaigns, and Account Groups represent groups of accounts.
The ID of the user who created the folder is used to complete the field.
Use the `GET /me` endpoint to get the current user ID.

| UI Display Name        | API Field Name                 | Example           |
| ---------------------- | ------------------------------ | ----------------- |
| Account Group ID       | `account_group_id`             |                   |
| Account Group Name     | `account_group_name`           |                   |
| Folder ID              | `folder_names.{id}`            | `folder_names.40` |
| Folder Name            | `folder_ids.{id}`              | `folder_ids.40`   |

#### Long IDs

Gives long form unique identifiers for each entity, matching ids generated by each remote network.
Note that `id`, while still maintained, refers to a legacy identification strategy that AdStage no longer uses, and therefore may be deprecated in the future.
Prefer the `entity_id` variants instead for uniquely identifying ads in application logic.

| UI Display Name        | API Field Name                 |
| ---------------------- | ------------------------------ |
| ID                     | `id`                           |
| Entity ID              | `entity_id`                    |
| Account Entity ID      | `account_entity_id`            |
| Campaign Entity ID     | `campaign_entity_id`           |
| Ad Group Entity ID     | `ad_group_entity_id`           |
| Ad Entity ID           | `ad_entity_id`                 |
| Keyword Entity ID      | `keyword_entity_id`            |

#### Entity Statuses

Gives the latest known status of the entity on the remote network (e.g. `COMPLETED`).
Note that the status does not necessarily correspond with the serving status.
For example, an ad marked "ACTIVE" may not be serving if its campaign is marked "INACTIVE".

| UI Display Name        | API Field Name                 |
| ---------------------- | ------------------------------ |
| Status                 | `status`                       |
| Account Status         | `account_status`               |
| Campaign Status        | `campaign_status`              |
| Ad Group Status        | `ad_group_status`              |
| Ad Status              | `ad_status`                    |
| Keyword Status         | `keyword_status`               |

#### Bid Information

Gives information regarding the bid on an entity.
Note that `bid_float` and `bid.value` represent the same data as a float and string respectively.

| UI Display Name        | API Field Name                 |
| ---------------------- | ------------------------------ |
| Bid                    | `bid_float`                    |
| Pretty Bid             | `bid.pretty_bid`               |
| Bid Title              | `bid.title`                    |
| Bid Subtitle           | `bid.subtitle`                 |
| Bid Type               | `bid.type`                     |
| Bid Value              | `bid.value`                    |

#### Budget Information

Gives information regarding the budget for an entity.
Note that `budget_float` and `budget.value` represent the same data as a float and string respectively.

| UI Display Name        | API Field Name                 |
| ---------------------- | ------------------------------ |
| Budget                 | `budget_float`                 |
| Pretty Budget          | `budget.pretty_budget`         |
| Budget Title           | `budget.title`                 |
| Budget Subtitle        | `budget.subtitle`              |
| Budget Type            | `budget.type`                  |
| Budget Value           | `budget.value`                 |

#### Objective Information

Gives information regarding the objective for an entity.
Note that AdStage stores these related fields formatted as JSON in the `objective` object.
To request a single, flattened objective field, append a dot and the key name, such as `objective.unit`.

| UI Display Name        | API Field Name                 |
| ---------------------- | ------------------------------ |
| Objective              | `objective`                    |
| Objective Code         | `objective.code`               |
| Objective Title        | `objective.title`              |
| Objective Subtitle     | `objective.subtitle`           |
| Objective Unit         | `objective.unit`               |

#### Entity Types

Gives information about the type or subtype for an entity as designated by the remote network.
For example, a LinkedIn campaign may have the `campaign_type` of `SSU`, a LinkedIn API designated campaign type.
Note that the `type` field is an exception and refers to an AdStage generated entity category, such as `network_ad`, rather than a remote network designated category.
See the Entity IDs section for more information.

| UI Display Name        | API Field Name                 |
| ---------------------- | ------------------------------ |
| Type                   | `type`                         |
| Campaign Type          | `campaign_type`                |
| Ad Type                | `ad_type`                      |
| Match Type             | `keyword_match_type`           |

#### Keyword/Criterion Information

Gives information describing a keyword or criterion.

| UI Display Name        | API Field Name                 |
| ---------------------- | ------------------------------ |
| Keyword Text           | `keyword_text`                 |
| Quality Score          | `quality_score_float`          |

#### Ad Information

Gives information describing an ad.

| UI Display Name        | API Field Name                 |
| ---------------------- | ------------------------------ |
| Ad Title               | `title`                        |
| Ad Headline            | `ad_headline`                  |
| Ad Description         | `description`                  |
| Update                 | `update`                       |
| Post Text              | `post_text`                    |

#### URL Information

Gives information about various URLs associated with an ad.

| UI Display Name        | API Field Name                 |
| ---------------------- | ------------------------------ |
| Destination URL        | `destination_url`              |
| Final URL              | `final_url`                    |
| Final Mobile URL       | `final_mobile_url`             |
| Image                  | `image_url`                    |
| SU Image               | `submitted_image_url`          |
| Tracking Template      | `tracking_url_template`        |

#### UTM Tracking Information

**Note: UTM tracking information is only available if AdStage Join has been added to your AdStage plan and a Join task has been completed for the entity.
Currently, Join is available only as a paid Add-On.**

Gives information about the UTM parameters associated with the entity.
Note that AdStage stores these parameters formatted as JSON in `tracking_params`.
To request a single, flattened parameter, append a dot and the key name, such as `tracking_params.utm_term`.

| UI Display Name        | API Field Name                 |
| ---------------------- | ------------------------------ |
| URL Tracking Params    | `tracking_params`              |
| UTM Medium             | `tracking_params.utm_medium`   |
| UTM Source             | `tracking_params.utm_source`   |
| UTM Campaign           | `tracking_params.utm_campaign` |
| UTM Content            | `tracking_params.utm_content`  |
| UTM Term               | `tracking_params.utm_term`     |
