### Network Metric Descriptors [GET /metric_descriptors/{network}]

AdStage's reporting endpoints allow developers to request data from non-AdStage reporting providers, normalized in a single, convenient format.
Ad network reporting providers can often provide real-time data and/or data that is not importable into AdStage's database, such as demographic dimensions from Facebook Direct.
However, separate metrics descriptors need to be loaded to properly specify fields in reports from remote ad networks; this endpoint provides information on the names and formats of these metrics.


Note that metric descriptors from non-AdStage reporting providers are currently considered separate from AdStage provider metric descriptors.
Descriptors may share the same `id` across providers but not necessarily associate to the same metrics (for example, the `clicks` metric from `facebook` provider reports actually matches the `total_clicks` metric in `adstage` provider reports).
Developers should therefore take care to maintain separate metric descriptor lists for each reporting provider accessed through the AdStage API.
Additionally, non-AdStage network provider metrics do not distinguish between meta and metric fields; instead, any response from this endpoint will include meta fields in the metric descriptors list (typically as `"TEXT"` type).

+ Parameters

    + network: facebook (string)

        which network you want descriptors for. Currently `"facebook"`, `"adwords"`, `"gemini"`, and `"google_analytics"` are supported.

+ Request

    + Headers

        Accept: application/json

+ Response 200

  A list of columns that are available to pull via the reporting endpoint.

  + Attributes

        + (array)
            + (object)
                + id: "clicks" (string) - the identifier assigned to the metric in reports
                + short_name: "Clicks" (string) - a short human readable name for the metric
                + display_names: ["Clicks"] (array[string]) - the network's list of allowable human readable display names for the metric; this key is omitted unless `adwords` was specified for the `network` param
                + name: "Clicks" (string) - the full human readable name for the metric used in AdStage UIs
                + tooltip: "Clicks shows how many times a user clicked on your ad" (string) - additional details about a metric, if available
                + format: "DEFAULT", "PERCENTAGE", "CURRENCY", "TEXT", "DECIMAL", "INTEGER" (enum, string) - format for the metric (default is integer)
                + type: "METRIC", "TEXT" (enum, string) - whether the descriptor is for a metric, or metadata
                + can_filter: true (boolean) - if the metric is allowed to be used in a filter field for a reporting request; this key is omitted unless `gemini` was specified for the `network` param
                + supports_filters: ["ACCOUNT_PERFORMANCE_REPORT"] (array[string]) - a list of all reports on the provider's network that allow filtering on the metric; this key is omitted unless `adwords` was specified for the `network` param
                + supports_zero_impressions: ["ACCOUNT_PERFORMANCE_REPORT"] (array[string]) - a list of all reports on the provider's network that maintain metrics even when the ad entity has not logged any impressions; this key is omitted unless `adwords` was specified for the `network` param
                + reports: ["ACCOUNT_PERFORMANCE_REPORT"] (array[string]) - a list of all reports on the provider's network that provide data for the metric; this key is omitted unless `adwords` was specified for the `network` param
                + is_adwords: true (boolean) - if the metric is valid for the Google Ads network
                + is_bing_ads: true (boolean) - if the metric is valid for the Microsoft Ads network
                + is_facebook: true (boolean) - if the metric is valid for the Facebook network
                + is_gemini: false (boolean) - if the metric is valid for the Gemini network; this key is omitted unless `gemini` was specified for the `network` param
                + is_google_analytics: false (boolean) - if the metric is valid for the Google Analytics network; this key is omitted unless `google_analytics` was specified for the `network` param
                + is_linkedin: true (boolean) - if the metric is valid for the LinkedIn network
                + is_twitter: true (boolean) - if the metric is valid for the Twitter network
                + is_account: true (boolean) - if the metric is valid for the account reporting level
                + is_campaign: true (boolean) - if the metric is valid for the campaign reporting level
                + is_ad_group: true (boolean) - if the metric is valid for the ad group reporting level
                + is_ad: true (boolean) - if the metric is valid for the ad reporting level
                + is_keyword: true (boolean) - if the metric is valid for keyword reporting level

  + Body

        [
            {
                "id": "reach",
                "short_name": "Reach",
                "name": "Reach",
                "is_default": true,
                "tooltip": "The number of people who saw your ads at least once. Reach is different from impressions, which may include multiple views of your ads by the same people.",
                "format": "DEFAULT",
                "type": "METRIC",
                "category": "PERFORMANCE",
                "default_sort_order": "DESC",
                "is_adwords": false,
                "is_bing_ads": false,
                "is_facebook": true,
                "is_linkedin": false,
                "is_twitter": false,
                "is_account": true,
                "is_campaign": true,
                "is_ad_group": true,
                "is_ad": true,
                "is_keyword": false,
                "is_post": false,
                "is_company_status_update": false,
                "show_increase_as": "POSITIVE"
            },
            {
                "id": "results",
                "short_name": "Results",
                "name": "Results",
                "is_default": true,
                "tooltip": "The number of outcomes you achieved in your ad campaign, based on the objective you selected.",
                "format": "DEFAULT",
                "type": "METRIC",
                "category": "PERFORMANCE",
                "default_sort_order": "DESC",
                "is_adwords": false,
                "is_bing_ads": false,
                "is_facebook": true,
                "is_linkedin": false,
                "is_twitter": false,
                "is_account": true,
                "is_campaign": true,
                "is_ad_group": true,
                "is_ad": true,
                "is_keyword": false,
                "is_post": false,
                "is_company_status_update": false,
                "show_increase_as": "POSITIVE"
            }
        ]
